-- 코드를 입력하세요
SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES
FROM(SELECT FOOD_TYPE, FAVORITES, RANK() OVER(PARTITION BY FOOD_TYPE ORDER BY FAVORITES DESC) AS RANK, REST_ID,REST_NAME
FROM REST_INFO)
WHERE RANK = 1
ORDER BY FOOD_TYPE DESC;





