-- 코드를 입력하세요
WITH INFO_TABLE AS (
    SELECT 
        YEAR(a.SALES_DATE) AS SALES_YEAR,
        MONTH(a.SALES_DATE) AS SALES_MONTH,
        b.GENDER, a.USER_ID
    FROM ONLINE_SALE a, USER_INFO b
    WHERE 
        a.USER_ID = b.USER_ID
        AND b.GENDER IS NOT NULL
)
SELECT
    SALES_YEAR AS "YEAR",
    SALES_MONTH AS "MONTH",
    GENDER,
    COUNT(DISTINCT USER_ID) AS USERS
FROM INFO_TABLE
GROUP BY SALES_YEAR, SALES_MONTH, GENDER
ORDER BY SALES_YEAR ASC, SALES_MONTH ASC, GENDER ASC;