-- 코드를 입력하세요
SELECT NAME, DATETIME
FROM (SELECT ROWNUM, I.NAME, I.DATETIME
        FROM ANIMAL_INS I LEFT OUTER JOIN ANIMAL_OUTS O
        ON I.ANIMAL_ID = O.ANIMAL_ID
        WHERE O.DATETIME IS NULL
        ORDER BY DATETIME ASC
         )
WHERE ROWNUM >=1 AND ROWNUM < 4
