-- 코드를 입력하세요
WITH TMP AS (
    SELECT B.PRODUCT_ID, A.PRODUCT_NAME, (A.PRICE*B.AMOUNT) AS TOTAL_SALES
    FROM FOOD_PRODUCT A JOIN FOOD_ORDER B
    ON A.PRODUCT_ID = B.PRODUCT_ID
    WHERE TO_CHAR(B.PRODUCE_DATE,'YYYY-MM-DD') LIKE '2022-05%'
    )

SELECT PRODUCT_ID , PRODUCT_NAME, SUM(TOTAL_SALES) AS TOTAL_SALES
FROM TMP
GROUP BY PRODUCT_ID, PRODUCT_NAME
ORDER BY 3 DESC, 1 ASC;