-- 코드를 입력하세요
-- 리뷰를 가장 많이 작성한 회원의 리뷰들을 조회

WITH COUNT AS (
    SELECT B.MEMBER_ID, COUNT(*) C
    FROM MEMBER_PROFILE A JOIN REST_REVIEW B
    ON A.MEMBER_ID = B.MEMBER_ID
    GROUP BY B.MEMBER_ID
)
SELECT A.MEMBER_NAME, B.REVIEW_TEXT, TO_CHAR(B.REVIEW_DATE,'YYYY-MM-DD') AS REVIEW_DATE
    FROM MEMBER_PROFILE A JOIN REST_REVIEW B
    ON A.MEMBER_ID = B.MEMBER_ID
    LEFT JOIN COUNT C
    ON C.MEMBER_ID = B.MEMBER_ID
    WHERE C.C = (SELECT MAX(C) FROM COUNT)
    ORDER BY 3 ASC, 2 ASC;
