-- 코드를 작성해주세요
SELECT I.ITEM_ID, I.ITEM_NAME, I.RARITY
FROM ITEM_INFO I JOIN ITEM_TREE T
ON I.ITEM_ID = T.ITEM_ID
JOIN ITEM_INFO R
ON R.ITEM_ID = T.PARENT_ITEM_ID
WHERE R.RARITY = 'RARE'
ORDER BY I.ITEM_ID DESC;