-- 코드를 입력하세요
SELECT DISTINCT A.CAR_ID
FROM(SELECT CAR_ID
     FROM CAR_RENTAL_COMPANY_CAR 
     WHERE CAR_TYPE = '세단') A 
     JOIN
     (SELECT CAR_ID
      FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
      WHERE TO_CHAR(START_DATE,'YYYY-MM-DD') LIKE '2022-10%') B
     ON A.CAR_ID = B.CAR_ID
ORDER BY 1 DESC;