-- 코드를 작성해주세요
WITH TEMP AS (
    SELECT EMP_NO, SUM(SCORE) AS S
    FROM HR_GRADE
    GROUP BY EMP_NO
)

SELECT S AS SCORE, A.EMP_NO, B.EMP_NAME, POSITION, EMAIL
FROM TEMP A JOIN HR_EMPLOYEES B
ON A.EMP_NO = B.EMP_NO
WHERE S = (SELECT MAX(S) FROM TEMP)
